
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[264] =
    {   0,
        0,    0,    0,    0,   73,   73,   84,   83,   81,   82,
       83,   69,   11,    5,    6,   14,   12,    1,   13,   83,
       15,   66,    2,    4,   18,   29,   20,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,    7,
        8,    9,   10,   14,   80,   78,   83,   73,   74,   70,
       83,    0,   76,   16,    0,   66,   68,    0,    0,    0,
        0,    0,    0,    0,    0,   77,   17,   23,    0,    0,
        3,   19,   22,   30,   21,   80,   80,   80,   80,   80,
       80,   80,   80,   40,   80,   80,   80,   80,   80,   46,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,

        0,   79,   73,   72,   71,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   68,    0,   67,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   42,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,    0,   75,    0,    0,
        0,   20,   18,    0,    0,   25,    0,   31,   32,   80,
       80,   80,   80,   80,   38,   80,   41,   43,   80,   45,
       80,   80,   80,   80,   80,   80,   80,   56,   57,   80,
       80,   80,   61,   80,   63,   24,   27,    0,    0,   26,
        0,   80,   34,   80,   80,   37,   80,   80,   80,   80,

       80,   80,   80,   52,   80,   80,   80,   80,   80,   80,
        0,   28,   64,   80,   35,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   59,   60,   80,
       65,   80,   80,   80,   80,   47,   80,   49,   80,   54,
       53,   80,   55,   80,   80,   80,   36,   80,   44,   80,
       80,   80,   80,   80,   33,   39,   48,   51,   50,   58,
       80,   62,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    1,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   31,   43,   44,   31,
       45,   46,   47,    1,    1,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   31,   31,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   31,   68,
       69,   31,   70,   71,   72,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    2,    1,    2,    2,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    2,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        2,    1
    } ;

static yyconst flex_int16_t yy_base[270] =
    {   0,
        0,   63,   71,   72,   77,   85,  509,  514,  514,  514,
      494,  514,  514,  514,  514,  486,   62,  514,   63,  141,
       80,   82,  478,  514,  471,   81,  470,    0,   82,   62,
       93,   58,   68,   82,   72,  111,   63,  114,   75,  514,
      514,  514,  514,  102,  485,  514,  473,    0,  514,  480,
      479,  480,  514,  514,  464,  144,  463,   86,  110,  116,
      151,  152,  162,  124,  127,  514,  514,  514,  462,  194,
      514,  514,  514,  514,  514,    0,  170,  160,  151,  179,
      175,  175,  185,    0,  180,  195,  191,  189,  184,    0,
      186,  200,  192,  201,  206,  228,  201,  200,  216,  206,

      473,  514,    0,  514,  514,  220,  239,  227,  460,  454,
      424,  309,  242,  221,  276,  222,  248,  216,  213,  237,
      244,  234,  234,  244,  240,  250,  253,  257,  259,    0,
      247,  265,  256,  266,  265,  277,  269,  274,  286,  288,
      276,  278,  296,  288,  288,  301,  182,  514,  170,  169,
      290,  514,  514,  288,  139,  514,  305,    0,    0,  310,
      308,  302,  305,  312,    0,  307,    0,    0,  303,    0,
      318,  323,  317,  312,  319,  337,  327,    0,    0,  329,
      331,  346,    0,  339,    0,  514,  514,  345,  129,  514,
      115,  352,    0,  344,  345,    0,  341,  352,  357,  358,

      364,  361,  362,  359,  368,  373,  359,  366,  361,  365,
      107,  514,  514,  367,    0,  369,  385,  382,  380,  398,
      390,  384,  389,  394,  388,  397,  403,    0,    0,  396,
      514,  408,  411,  404,  406,    0,  420,    0,  419,    0,
        0,  410,    0,  408,  421,  418,    0,  423,    0,  432,
      424,  440,  441,  435,    0,    0,    0,    0,    0,    0,
      446,    0,  514,  498,  501,  504,  102,  507,  510
    } ;

static yyconst flex_int16_t yy_def[270] =
    {   0,
      263,    1,  264,  264,  265,  265,  263,  263,  263,  263,
      266,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  263,
      263,  263,  263,  263,   29,  263,  263,  268,  263,  263,
      263,  266,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      269,  263,  268,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  269,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  263,  263,  263,  263,  263,
      263,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      263,  263,  263,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      263,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,    0,  263,  263,  263,  263,  263,  263
    } ;

static yyconst flex_int16_t yy_nxt[587] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   28,   29,   30,   31,   32,   33,   28,   34,
       28,   35,   28,   28,   28,   36,   28,   37,   38,   39,
       28,   28,   28,   28,   40,    8,   41,   28,   28,   29,
       30,   31,   32,   33,   28,   34,   35,   28,   28,   28,
       36,   28,   37,   38,   39,   28,   28,   28,   28,   42,
        8,   43,   44,   46,   46,   55,   55,   56,   56,   49,
       47,   47,   50,   82,    8,    8,   45,   49,   96,   66,
       50,   83,    8,    8,   67,   69,   84,   56,   88,   68,

       73,   74,   89,   77,   76,  101,   92,   70,   90,   82,
       78,   54,   45,   79,   96,   91,   80,   83,  100,  106,
      231,   84,   51,   88,   85,   81,   86,   89,  213,   77,
       51,   92,   93,   70,   90,   87,   78,  108,   79,   97,
       91,   80,  212,  100,  106,   94,  107,    8,   95,   85,
       81,   86,  190,   98,   99,    8,   57,   69,   93,   56,
       87,  115,   58,  108,  116,   97,   59,   60,   61,   70,
       94,  107,   62,   95,   63,   64,  109,  111,   98,   99,
       65,  122,  187,  186,  148,  123,  115,  113,   58,  116,
      110,  112,   59,   60,   61,   70,  114,   62,  126,   63,

       64,  120,  109,  111,  118,   65,  118,  122,  121,  119,
      123,  124,  125,  113,  127,  110,  112,  128,  129,  130,
      131,  114,  132,  133,  126,  134,  120,  135,  119,  136,
      137,  119,  143,  121,  144,  138,  124,  125,  145,  127,
      139,  146,  128,  129,  149,  130,  131,  132,  133,  140,
      134,  141,   73,  135,  136,   68,  137,  143,  151,  144,
      155,  138,  157,  117,  145,  139,  146,  142,  158,  159,
      149,  160,  161,   70,  165,  140,  162,  141,  154,  163,
      150,  164,  166,  151,  167,  155,  168,  157,  169,  156,
      170,  171,  142,  158,  172,  159,  160,  161,  173,   70,

      165,  162,  174,  154,  163,  150,  164,  175,  166,  176,
      167,  168,  178,  177,  169,  170,  180,  171,  181,  179,
      172,  182,  153,  183,  173,  184,  185,  174,  188,  189,
      191,  192,  175,  193,  195,  176,  194,  196,  178,  177,
      197,  180,  198,  181,  179,  199,  201,  182,  183,  202,
      184,  203,  185,  188,  189,  200,  191,  192,  204,  193,
      195,  194,  205,  196,  206,  197,  207,  198,  208,  209,
      211,  199,  201,  210,  202,  214,  203,  215,  216,  217,
      200,  218,  219,  204,  220,  221,  222,  223,  205,  206,
      224,  207,  225,  208,  226,  209,  211,  227,  210,  228,

      229,  214,  215,  216,  217,  230,  232,  218,  219,  233,
      220,  221,  222,  223,  234,  224,  235,  236,  225,  237,
      226,  238,  227,  239,  228,  229,  240,  241,  242,  243,
      230,  232,  244,  246,  233,  245,  247,   72,  248,  249,
      234,  235,  236,  250,  251,  237,  238,  252,  239,  253,
      254,  240,  241,  242,  243,  255,  256,  257,  244,  246,
      245,  258,  247,  248,  249,  259,  260,  152,  261,  250,
      251,  262,  252,   75,  253,  148,  254,  117,   57,   57,
      255,  256,   53,  257,  105,  104,  258,  102,  101,   75,
       72,  259,  260,  261,   71,   54,   53,  262,    8,    8,

        8,   48,   48,   48,   52,   52,   52,  103,  263,  103,
      147,  147,  147,    7,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263
    } ;

static yyconst flex_int16_t yy_chk[587] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    3,    4,   17,   19,   17,   19,    5,
        3,    4,    5,   30,    5,    5,    2,    6,   37,   21,
        6,   30,    6,    6,   21,   22,   30,   22,   32,   21,

       26,   26,   33,   29,  267,   44,   35,   22,   34,   30,
       29,   44,    2,   29,   37,   34,   29,   30,   39,   58,
      211,   30,    5,   32,   31,   29,   31,   33,  191,   29,
        6,   35,   36,   22,   34,   31,   29,   60,   29,   38,
       34,   29,  189,   39,   58,   36,   59,    5,   36,   31,
       29,   31,  155,   38,   38,    6,   20,   56,   36,   56,
       31,   64,   20,   60,   65,   38,   20,   20,   20,   56,
       36,   59,   20,   36,   20,   20,   61,   62,   38,   38,
       20,   78,  150,  149,  147,   79,   64,   63,   20,   65,
       61,   62,   20,   20,   20,   56,   63,   20,   81,   20,

       20,   77,   61,   62,   70,   20,   70,   78,   77,   70,
       79,   80,   80,   63,   82,   61,   62,   83,   85,   86,
       87,   63,   88,   89,   81,   91,   77,   92,  119,   93,
       94,  118,   97,   77,   98,   95,   80,   80,   99,   82,
       95,  100,   83,   85,  106,   86,   87,   88,   89,   96,
       91,   96,  107,   92,   93,  113,   94,   97,  108,   98,
      114,   95,  116,  117,   99,   95,  100,   96,  120,  121,
      106,  122,  123,  117,  127,   96,  124,   96,  113,  125,
      107,  126,  128,  108,  129,  114,  131,  116,  132,  115,
      133,  134,   96,  120,  135,  121,  122,  123,  136,  117,

      127,  124,  137,  113,  125,  107,  126,  138,  128,  139,
      129,  131,  140,  139,  132,  133,  141,  134,  142,  140,
      135,  143,  112,  144,  136,  145,  146,  137,  151,  154,
      157,  160,  138,  161,  163,  139,  162,  164,  140,  139,
      166,  141,  169,  142,  140,  171,  172,  143,  144,  173,
      145,  174,  146,  151,  154,  171,  157,  160,  175,  161,
      163,  162,  176,  164,  177,  166,  180,  169,  181,  182,
      188,  171,  172,  184,  173,  192,  174,  194,  195,  197,
      171,  198,  199,  175,  200,  201,  202,  203,  176,  177,
      204,  180,  205,  181,  206,  182,  188,  207,  184,  208,

      209,  192,  194,  195,  197,  210,  214,  198,  199,  216,
      200,  201,  202,  203,  217,  204,  218,  219,  205,  220,
      206,  221,  207,  222,  208,  209,  223,  224,  225,  226,
      210,  214,  227,  232,  216,  230,  233,  111,  234,  235,
      217,  218,  219,  237,  239,  220,  221,  242,  222,  244,
      245,  223,  224,  225,  226,  246,  248,  250,  227,  232,
      230,  251,  233,  234,  235,  252,  253,  110,  254,  237,
      239,  261,  242,  109,  244,  101,  245,   69,   57,   55,
      246,  248,   52,  250,   51,   50,  251,   47,   45,   27,
       25,  252,  253,  254,   23,   16,   11,  261,  264,  264,

      264,  265,  265,  265,  266,  266,  266,  268,    7,  268,
      269,  269,  269,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lex.l"
#line 2 "Lex.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "Yacc.tab.h"
#include "SymbolTable.h"

#define YYLVAL(t) yylval = (YYSTYPE)t
#define OUT_SIZE 4096
#define MAX_STR_SIZE 2048

long int lineNo = 0;
char outputBuff[OUT_SIZE], strBuff[MAX_STR_SIZE];	// outputBuff stores token tags in current line.

void printTokenOrd(char *text){
	fprintf(stdout, "<%s>\r\n", text);
}

void printToken(char *text, char *tokenType){
		fprintf(stdout, "<\033[38;5;46m%s\033[0;0m: \033[38;5;204m%s\033[0;0m> @ line %ld\r\n", tokenType, text, lineNo);
}

void newLine(){	// Gives a new line
	// Increase lineNo, and prints all token tags of previous line.
	// And then gives new line No. 
	lineNo++;
	//-- fprintf(stdout, "\r\n%s\033[38;5;190m%ld\033[0;0m: ", outputBuff, lineNo);
	//-- outputBuff[0] = '\0';
	//-- fprintf(stdout, "%s\r\n", outputBuff);
	//-- fflush(stdout);
}



#line 710 "lex.yy.c"

#define INITIAL 0
#define COMMENTS 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 42 "Lex.l"


	/* delimiter begin */ 
#line 906 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 264 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 514 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_COMMA;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_COLON;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_DUAL_COLON;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_SEMICOLON;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_L_PARENTHESIS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_R_PARENTHESIS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_L_SQUARE_BRACKET;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_R_SQUARE_BRACKET;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_L_BRACKET;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 54 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_R_BRACKET;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 55 "Lex.l"
{ printToken(yytext, "delimiter"); return DEL_COMPONENT_REF;}
	YY_BREAK
/* delemiter end */
/* operators begin */
/*	Arithmatic */
case 12:
YY_RULE_SETUP
#line 60 "Lex.l"
{ printToken(yytext, "operator"); return OP_ADD;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "Lex.l"
{ printToken(yytext, "operator"); return OP_SUB;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "Lex.l"
{ printToken(yytext, "operator"); return OP_MULTIPLY;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "Lex.l"
{ printToken(yytext, "operator"); return OP_DIVIDE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "Lex.l"
{ printToken(yytext, "operator"); return OP_EXPONENT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "Lex.l"
{ printToken(yytext, "operator"); return OP_CONCAT;}
	YY_BREAK
/*	Relation */
case 18:
YY_RULE_SETUP
#line 68 "Lex.l"
{ printToken(yytext, "operator"); return OP_LT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "Lex.l"
{ printToken(yytext, "operator"); return OP_LE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "Lex.l"
{ printToken(yytext, "operator"); return OP_GT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "Lex.l"
{ printToken(yytext, "operator"); return OP_GE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "Lex.l"
{ printToken(yytext, "operator"); return OP_EQ;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "Lex.l"
{ printToken(yytext, "operator"); return OP_NE;}
	YY_BREAK
/*	Logic */
case 24:
YY_RULE_SETUP
#line 76 "Lex.l"
{ printToken(yytext, "operator"); return OP_AND;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "Lex.l"
{ printToken(yytext, "operator"); return OP_OR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "Lex.l"
{ printToken(yytext, "operator"); return OP_NOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "Lex.l"
{ printToken(yytext, "operator"); return OP_EQV;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "Lex.l"
{ printToken(yytext, "operator"); return OP_NEQV;}
	YY_BREAK
/*	Assign */
case 29:
YY_RULE_SETUP
#line 83 "Lex.l"
{ printToken(yytext, "operator"); return OP_ASSIGN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "Lex.l"
{ printToken(yytext, "operator"); return OP_POINTER_ASSIGN;};
	YY_BREAK
/* operators end */
/* keywords begin */
case 31:
YY_RULE_SETUP
#line 88 "Lex.l"
{ printToken(yytext, "keyword"); return KW_CALL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "Lex.l"
{ printToken(yytext, "keyword"); return KW_CASE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 90 "Lex.l"
{ printToken(yytext, "keyword"); return KW_CHAR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 91 "Lex.l"
{ printToken(yytext, "keyword"); return KW_CLOSE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "Lex.l"
{ printToken(yytext, "keyword"); return KW_COMMON;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 93 "Lex.l"
{ printToken(yytext, "keyword"); return KW_CONT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 94 "Lex.l"
{ printToken(yytext, "keyword"); return KW_CYCLE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 95 "Lex.l"
{ printToken(yytext, "keyword"); return KW_DATA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 96 "Lex.l"
{ printToken(yytext, "keyword"); return KW_DIM;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "Lex.l"
{ printToken(yytext, "keyword"); return KW_DO;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "Lex.l"
{ printToken(yytext, "keyword"); return KW_ELSE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "Lex.l"
{ printToken(yytext, "keyword"); return KW_END;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "Lex.l"
{ printToken(yytext, "keyword"); return KW_EXIT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "Lex.l"
{ printToken(yytext, "keyword"); return KW_FUNC;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "Lex.l"
{ printToken(yytext, "keyword"); return KW_GOTO;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "Lex.l"
{ printToken(yytext, "keyword"); return KW_IF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "Lex.l"
{ printToken(yytext, "keyword"); return KW_INT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 105 "Lex.l"
{ printToken(yytext, "keyword"); return KW_INTERFACE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "Lex.l"
{ printToken(yytext, "keyword"); return KW_LOGIC;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 107 "Lex.l"
{ printToken(yytext, "keyword"); return KW_PROCEDURE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 108 "Lex.l"
{ printToken(yytext, "keyword"); return KW_PARAMETER;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 "Lex.l"
{ printToken(yytext, "keyword"); return KW_PRINT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "Lex.l"
{ printToken(yytext, "keyword"); return KW_PRINTLN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "Lex.l"
{ printToken(yytext, "keyword"); return KW_POINTER;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "Lex.l"
{ printToken(yytext, "keyword"); return KW_PROGRAM;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "Lex.l"
{ printToken(yytext, "keyword"); return KW_PROGRAM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "Lex.l"
{ printToken(yytext, "keyword"); return KW_REAL;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "Lex.l"
{ printToken(yytext, "keyword"); return KW_RECURSIVE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "Lex.l"
{ printToken(yytext, "keyword"); return KW_RETURN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 117 "Lex.l"
{ printToken(yytext, "keyword"); return KW_SELECT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 118 "Lex.l"
{ printToken(yytext, "keyword"); return KW_STOP;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 119 "Lex.l"
{ printToken(yytext, "keyword"); return KW_SUB;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 120 "Lex.l"
{ printToken(yytext, "keyword"); return KW_TYPE;}
	YY_BREAK
/* keywords end */
/* booleans begin */
case 64:
YY_RULE_SETUP
#line 124 "Lex.l"
{ printToken(yytext, "boolean"); yylval.Zval = 1; return CONST_BOOL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 125 "Lex.l"
{ printToken(yytext, "boolean"); yylval.Zval = 0; return CONST_BOOL;}
	YY_BREAK
/* booleans end */
/* integers begin */
case 66:
YY_RULE_SETUP
#line 129 "Lex.l"
{
				printToken(yytext, "integer");
				sscanf(yytext, "%d", &(yylval.Zval));
				return CONST_INT;
			}
	YY_BREAK
/* integers end */
/* real numbers */
case 67:
YY_RULE_SETUP
#line 137 "Lex.l"
{
							printToken(yytext, "real");
							sscanf(yytext, "%lf", &(yylval.Rval));
							return CONST_REAL;
						}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "Lex.l"
{
							printToken(yytext, "real");
							sscanf(yytext, "%lf", &(yylval.Rval));
							return CONST_REAL;
						}
	YY_BREAK
/* real numbers */
/* strings begin */
case 69:
YY_RULE_SETUP
#line 150 "Lex.l"
{ 
		// Start string pattern
		BEGIN(STRING);
		strBuff[0] = '\0'; 
	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 155 "Lex.l"
{
		// Met one double-quote implies string ends. Complete the string tag and back to initial state.
		BEGIN(INITIAL);
		printToken(strBuff, "string");
		memcpy(yylval.Str, strBuff, strlen(strBuff)+1);
		return CONST_STRING;
	}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 162 "Lex.l"
{
		// Met a slash and a double-quote implies a double-quote in string.
		sprintf(strBuff, "%s%c", strBuff, (char)0x22);
	}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 166 "Lex.l"
{
		// Met two double-quote implies a double-quote in string.
		sprintf(strBuff, "%s%c", strBuff, (char)0x22);
	}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 170 "Lex.l"
{
		// Met anything neither double-quote nor line break then it is a part of string. Store it.
		sprintf(strBuff, "%s%s", strBuff, yytext);
	}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 174 "Lex.l"
{
		// Met a line break in the string implies it's an un-closed string.
		fprintf(stdout, "\033[38;5;196mun-closed String\033[0;0m @ line %ld\r\n", lineNo);
		newLine();
		BEGIN(INITIAL);
		return C_LF;
	}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 181 "Lex.l"
{
		// Reach the end-of-file in the string implies it's an un-closed string.
		fprintf(stdout, "\033[38;5;196mun-closed String\033[0;0m @ line %ld\r\n", lineNo);
		BEGIN(INITIAL);
		return C_EOF;
	}
	YY_BREAK
/* strings end */
/* comments begin */
case 75:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 190 "Lex.l"
{ fprintf(stdout, "\033[38;5;247m%s\033[0;0m\r\n", yytext); }
	YY_BREAK
case 76:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 191 "Lex.l"
{ fprintf(stdout, "\033[38;5;247m%s\033[0;0m\r\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 192 "Lex.l"
{
		fprintf(stdout, "\033[38;5;247m%s", yytext);
		BEGIN(COMMENTS);
	}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 196 "Lex.l"
{ newLine(); fprintf(stdout, "\033[38;5;247m"); return C_LF;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 197 "Lex.l"
{
		fprintf(stdout, "%s\033[0;0m", yytext);
		BEGIN(INITIAL);
	}
	YY_BREAK
case YY_STATE_EOF(COMMENTS):
#line 201 "Lex.l"
{
		fprintf(stdout, "\r\n\t%s\033[38;5;196mun-closed Comment\033[0;0m @ line %ld\r\n", outputBuff, lineNo);
		BEGIN(INITIAL); 
		return C_EOF;
	}
	YY_BREAK
/* comments end */
/* identifiers begin */
case 80:
YY_RULE_SETUP
#line 209 "Lex.l"
{ 
		printToken(yytext, "identifier");
		if(lookup(current, yytext) == NULL)
			insert(current, yytext);
		memcpy(yylval.Str, yytext, strlen(yytext)+1);
		return IDENTIFIER;
	}
	YY_BREAK
/* identifiers end */
case 81:
YY_RULE_SETUP
#line 218 "Lex.l"
{ /*fprintf(stdout, "%s", yytext);*/ }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 219 "Lex.l"
{ printToken("C_LF", "LineBreak"); newLine(); return C_LF;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 220 "Lex.l"
{ return C_EOF;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 221 "Lex.l"
ECHO;
	YY_BREAK
#line 1505 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 264 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 264 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 263);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 221 "Lex.l"



/*int t_main(int argc, char *argv[]){
	if(argc>1){
		yyin = fopen(argv[1],"r");
		if(yyin != NULL)
			fprintf(stdout, "\033[38;5;46mScanning from file %s\033[0;0m\r\n", argv[1]);
		else
			fprintf(stdout, "\033[38;5;46mScanning from stdin\033[0;0m\r\n");
	}else
		fprintf(stdout, "\033[38;5;46mScanning from stdin\033[0;0m\r\n");
	create(NULL);
	outputBuff[0] = '\0';
	newLine();
	yylex();
	dump(current);
	fprintf(stdout, "\r\n\033[38;5;46mEnd of scanning\033[0;0m\r\n");
	release(current);
	return 0;
}*/
